### ISSUE TITLE
On heroku server content isn't updating

### ISSUE THREAD

**Issue by AndrewNB** [moltin/react-demo-store#45]
Hi, thanks for this project.  

I have a question re deployment.  I have changed the moltin account details to mine, set up my own categories and added other content and redesigned to fit my needs.  Running locally, everything runs great.  Once I deploy to heroku, all of the content from Moltin gets replaced with the lamp store's account.  Any tips on re-caching and deploying?

**Comment by notrab** [comment]
Hey @andrewNB

See https://forum.moltin.com/t/deploy-version-showing-demo-products/1156/4

I imagine this is the same issue and that it is you also posting there 😜
