### ISSUE TITLE
Setup with Stripe

### ISSUE THREAD

**Issue by centrepocket** [moltin/react-demo-store#47]
Can I ask how I could incorporate stripe payments through the checkout form.  It seems to use a template on checkout for the payment form.  How could I use the form with something like stripe elements?

Thanks

**Comment by notrab** [comment]
Hi @centrepocket 

While this example is a little out of date and could use some TLC, it wouldn't be too difficult to integrate what we have with the nextjs-demo-store here.

See https://github.com/moltin-examples/nextjs-demo-store/blob/73d74efaf3d7dc749fa1104d5e2b698b7e314c7a/components/CartSummary.js for how to use `react-stripe-checkout`.
